auto: true
# Url to append to all links.
url: 
permalink: /:year/:title

# Url for dropbox.
# Dropbox allows us to serve html content using the public folder.
# A dropbox url will have the following format:
# https://dl.dropboxusercontent.com/u/USER_ID/

# Custom information
title: jekyll
description: Simple static site generator
author: Daniel Silva